import { Geist, Geist_Mono } from "next/font/google";

import NavBar from "@/components/NavBar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VOX AI DOCTOR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[url('/images/bg.jpg')] w-[100vw] h-[100vh] antialiased  bg-cover bg-center bg-no-repeat`}
      >
      <div className="flex gap-7 flex-col w-[100vw] h-[100vh] bg-gradient-to-r from-[#000]/60 to-[#000]/60">
      <NavBar />
        {children}
        </div>
      </body>
    </html>
  );
}
